In [1]:
print('Hello world!')

Hello world!


In [2]:
import tweepy

ModuleNotFoundError: No module named 'tweepy'

In [9]:
a = 100
print(type(a))

<class 'int'>


In [3]:
a = 100
a = a*2    # equivalent to (shorter) a*=2
b = 50
c = a + b
print(a, b, c)

200 50 250


In [21]:
d = 20
print(type(d))
# forcing python to ctreat 20 as a float
d2 = 20.0
print(type(d2))

e = int(20.7)
print(type(e))
print(e)

f = True
print(type(f))
print(int(f))
print(int(False))

<class 'int'>
<class 'float'>
<class 'int'>
20
<class 'bool'>
1
0


In [28]:
sometext = "I like Python!"
print(type(sometext))
somebytes = b"I like Python!"
print(type(somebytes))

print("'Hi!' said he.")
print('"Hi!" said he.')

<class 'str'>
<class 'bytes'>
'Hi!' said he.
"Hi!" said he.


In [39]:
my_list = [1, 0, -1, 'positive', 'neutral', 'negative']
my_tuple = (1, 0, -1, 'positive', 'neutral', 'negative')
print(len(my_list), len(my_tuple))

# indexing
print(my_list[4])
print(my_tuple[3:5])

#let's add another element, and also change 'neutral' to 'informative
my_list.append('something')
my_list[4] = 'informative'

# both of the following will cause an error, because tuples are immutable
my_tuple.append(4)
my_tuple[4] = 'informative'

6 6
neutral
('positive', 'neutral')


AttributeError: 'tuple' object has no attribute 'append'

In [42]:
colours = set(['blue', 'yellow', 'red'])
# or simply:
colours2 = {'blue', 'yellow', 'red'}

colours3 = frozenset(['blue', 'yellow', 'red'])

print(type(colours), type(colours2), type(colours3))

<class 'set'> <class 'set'> <class 'frozenset'>


In [44]:
import numpy as np
scores_as_list = [8, 8, 7, 6, 9, 4, 9, 2, 8, 5,  'b']
print(scores_as_list)
scores_as_array = np.array(scores_as_list)
print(scores_as_array)

[8, 8, 7, 6, 9, 4, 9, 2, 8, 5, 'b']
['8' '8' '7' '6' '9' '4' '9' '2' '8' '5' 'b']


In [34]:
l1 = [1,2,3,4]
l2 = l1   # in R, this would create a copy, but here, we just create a reference!
l2.append(5)
# l1 is changed as well!!!
print(l1)

# if you want to create a copy of a *mutable* object, use .copy() instead:
l1 = [1,2,3,4]
l2 = l1.copy()
l2.append(5)
print(l1)


# strings, instead, are *immutable*, which means that a copy is created anyway:
s1 = "hi"
s2 = s1 + "you"
# s1 is still unchanged
print(s1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4]
hi


In [46]:
sentiments = {"positive" : 1, "neutral" : 0, "negative" : -1}
print(type(sentiments))

grades =  {}
grades['A'] = 4
grades['B'] = 3
grades['C'] = 2
grades['D'] = 1
print(grades)
print(sentiments['positive'])
print(grades['A'])

<class 'dict'>
{'A': 4, 'B': 3, 'C': 2, 'D': 1}
1
4


In [77]:
import numpy as np

matrix = [[1, 2, 3], [4, 5, 6], [7,8,9]]
print(matrix)

array2d = np.array(matrix)
print(array2d)

array3d = np.array(([['green', 'green', 'green'], ['yellow', 'yellow', 'yellow'], ['red', 'red', 'red']], 
          [['green', 'green', 'green'], ['yellow', 'yellow', 'yellow'], ['red', 'red', 'red']],
          [['green', 'green', 'green'], ['yellow', 'yellow', 'yellow'], ['red', 'red', 'red']]))
print(array3d.shape)
print(array3d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3, 3)
[[['green' 'green' 'green']
  ['yellow' 'yellow' 'yellow']
  ['red' 'red' 'red']]

 [['green' 'green' 'green']
  ['yellow' 'yellow' 'yellow']
  ['red' 'red' 'red']]

 [['green' 'green' 'green']
  ['yellow' 'yellow' 'yellow']
  ['red' 'red' 'red']]]


In [82]:
import pandas as pd
authors = pd.DataFrame({'age': [38, 36, 39], 'countries': ['Netherlands', 'Germany', 'Spain'], 'living_abroad': [False, True, True]})
print(authors)

   age    countries  living_abroad
0   38  Netherlands          False
1   36      Germany           True
2   39        Spain           True


In [89]:
#This script in Python creates two simple functions to estimate the 60% of any given number                               

#The first function computes the 60% always                                                                               
def por_60(x):
  return x*0.6
print (por_60(10))
print (por_60(4))

#The second function computes the 60% ONLY IF the argument is above 5,                                                    
# and the other cases the function returns the very same argument
def por_60_cond(x):
  if x>5:
    return x*0.6
  else:
    return x
print (por_60_cond(10))
print (por_60_cond(4))

6.0
2.4
6.0
4


In [88]:
#Create the list with the scores and then apply a simple loop
scores = [3,4,5,6,7]
for x in scores:
  print(por_60_cond(x))

3
4
5
3.5999999999999996
4.2


In [91]:
#This script creates in Python a list of headlines and shows two ways to count the number of characters of each string
#We create a list of headlines (strings):
headlines = ('US condemns South new terrorist  attacks', 'New elections forces UK to go back to the UE', 'Venezuelan president is dismissed')
#The first way is manual:
print('manual results:')
print(len(headlines[0]))
print(len(headlines[1]))
print(len(headlines[2]))
#and the second is using a for-loop
print('for-loop results:')
for x in headlines:
    print(len(x))

manual results:
40
44
33
for-loop results:
40
44
33


In [94]:
len_headlines= [len(x) for x in headlines]
print(len_headlines)

# The code above is a really useful shorthand and considered very 'pythonic'.
# It is equivalent to the more verbose code below:
len_headlines = []
for x in headlines:
    len_headlines.append(len(x))
print(len_headlines)

[40, 44, 33]
[40, 44, 33]


In [97]:
#Print the headline if it is < 40 characters
for x in headlines:                                                                                                       
  if len(x)<40:                                                                                                           
    print(x)

Venezuelan president is dismissed


In [99]:
#Print the headline if it is < 40 characters and print 'NaN' in the other cases
for x in headlines:
  if len(x)<40:
    print(x)
  elif len(x) == 44:
    print("What a coincidence!")
  else :
    print ('NaN')


NaN
What a coincidence!
Venezuelan president is dismissed
