In [1]:
!pip3 install numpy pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
print('Hello world!')

Hello world!


In [4]:
a = 100
print(type(a))

<class 'int'>


In [5]:
a = 100
a = a*2    # equivalent to (shorter) a*=2
b = 50
c = a + b
print(a, b, c)

200 50 250


In [6]:
d = 20
print(type(d))
# forcing python to treat 20 as a float
d2 = 20.0
print(type(d2))

e = int(20.7)
print(type(e))
print(e)

f = True
print(type(f))
print(int(f))
print(int(False))

<class 'int'>
<class 'float'>
<class 'int'>
20
<class 'bool'>
1
0


In [7]:
text1 = "This is a text"
print(f"Type of text1: {type(text1)}")
text2 = "Using 'single' and \"double\" quotes"
text3 = 'Using \'single\' and "double" quotes'
print(f"Are text2 and text3 equal? {text2 == text3}")

Type of text1: <class 'str'>
Are text2 and text3 equal? True


In [8]:
somebytes= text1.encode("utf-8")
print(type(somebytes))
print(somebytes)

<class 'bytes'>
b'This is a text'


In [9]:
scores = [8, 8, 7, 6, 9, 4, 9, 2, 8, 5]
print(type(scores))
countries = ['Netherlands', 'Germany', 'Spain']
print(type(countries))


<class 'list'>
<class 'list'>


In [10]:
scores = ["8", "8", "7", "6", "9", "4", "9", "2", "8", "5"]

print(scores[4])
print([scores[0], scores[9]])
print(scores[0:4])

# taking the first 4 elements from scores and convert them back into numbers
# the technique used here is a "list comprehension", which we explain in the section on loops and conditions
scores_new = [int(e) for e in scores[1:4]]
print(type(scores_new))
print(scores_new)

9
['8', '5']
['8', '8', '7', '6']
<class 'list'>
[8, 7, 6]


In [11]:
# appending a new value to a list
scores.append(7)

# Of course, we could also store it in a different object instead of overwriting the original list
scores4 = scores + [7]

# removing an entr
del scores[-10]

# creating a list containing the values 1,2,3,...20 (or -5, -4, ... 5)
list(range(1,21)) 
list(range(-5,6))    

# more advanced: 0, 0.2, 0.4, ... 1.0 
# because range only handles integers, we create the integers 0, 2, 4 .. 10 (we start at 0, stop before we reach 11, and take steps of 2) and then divide each value by 10.
# the technique used here is a "list comprehension", which we explain in the section on loops and conditions
my_sequence = [e/10 for e in range(0,11,2)]

In [12]:
my_list = [33, 'Twitter', np.sqrt, [1,2,3,4]]
print(type(my_list))

# this resolves to sqrt(16):
print(my_list[2](16))

<class 'list'>
4.0


In [13]:
x = [1,2,3]
y = x
y[0] = 99
print(x)

[99, 2, 3]


In [14]:
my_tuple = (1, 2, 3)
# Note that you can also omit the parentheses:
my_tuple = 1, 2, 3  
print(type(my_tuple))

<class 'tuple'>


In [15]:
a = {3, 4, 5}
my_list = [3, 2, 3, 2, 1]
b = set(my_list)
print(f"Set a: {a}; b: {b}")
print(f"intersect:  a & b = {a & b}")
print(f"union:      a | b = {a | b}")
print(f"difference: a - b = {a - b}")


Set a: {3, 4, 5}; b: {1, 2, 3}
intersect:  a & b = {3}
union:      a | b = {1, 2, 3, 4, 5}
difference: a - b = {4, 5}


In [16]:
my_list = [1, 0, -1, 'positive', 'neutral', 'negative']
my_tuple = (1, 0, -1, 'positive', 'neutral', 'negative')
print(len(my_list), len(my_tuple))

# indexing
print(my_list[4])
print(my_tuple[3:5])

#let's add another element, and also change 'neutral' to 'informative'
my_list.append('something')
my_list[4] = 'informative'

# both of the following will cause an error, because tuples are immutable
my_tuple.append(4)
my_tuple[4] = 'informative'

6 6
neutral
('positive', 'neutral')


AttributeError: 'tuple' object has no attribute 'append'

In [17]:
colours = set(['blue', 'yellow', 'red'])
# or simply:
colours2 = {'blue', 'yellow', 'red'}

colours3 = frozenset(['blue', 'yellow', 'red'])

print(type(colours), type(colours2), type(colours3))

<class 'set'> <class 'set'> <class 'frozenset'>


In [18]:
import numpy as np
scores_as_list = [8, 8, 7, 6, 9, 4, 9, 2, 8, 5,  'b']
print(scores_as_list)
scores_as_array = np.array(scores_as_list)
print(scores_as_array)

[8, 8, 7, 6, 9, 4, 9, 2, 8, 5, 'b']
['8' '8' '7' '6' '9' '4' '9' '2' '8' '5' 'b']


In [19]:
sentiments = {"positive" : 1, "neutral" : 0, "negative" : -1}
print(type(sentiments))
print(f"Sentiment for positive: {sentiments['positive']}")

grades =  {}
grades['A'] = 4
grades['B'] = 3
grades['C'] = 2
grades['D'] = 1

print(f"Grade for A: {grades['A']}")
print(grades)

<class 'dict'>
Sentiment for positive: 1
Grade for A: 4
{'A': 4, 'B': 3, 'C': 2, 'D': 1}


In [20]:
matrix = [[1, 2, 3], [4, 5, 6], [7,8,9]]
print(matrix)

array2d = np.array(matrix)
print(array2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
authors = pd.DataFrame({'age': [38, 36, 39], 'countries': ['Netherlands', 'Germany', 'Spain'], 'living_abroad': [False, True, True]})
print(authors)

   age    countries  living_abroad
0   38  Netherlands          False
1   36      Germany           True
2   39        Spain           True


In [22]:
#This script in Python creates two simple functions to estimate the 60% of any given number                               

#The first function computes the 60% always                                                                               
def por_60(x):
  return x*0.6
print (por_60(10))
print (por_60(4))

#The second function computes the 60% ONLY IF the argument is above 5,                                                    
# and the other cases the function returns the very same argument
def por_60_cond(x):
  if x>5:
    return x*0.6
  else:
    return x
print (por_60_cond(10))
print (por_60_cond(4))

6.0
2.4
6.0
4


In [23]:
#Create the list with the scores and then apply a simple loop
scores = [3,4,5,7]
for x in scores:
  print(por_60_cond(x))

3
4
5
4.2


In [24]:
mylist = [35,2,464,4]

def square1(somelist):
    listofsquares = []
    for i in somelist:
        listofsquares.append(i**2)
    return(listofsquares)

def square2(somelist):
    for i in somelist:
        yield i**2

print("As a list:")
mysquares = square1(mylist)
for mysquare in mysquares:
    print(mysquare)
print(type(mysquares))
print(f"The list has {len(mysquares)} entries")

    
print("\nAs a generator:")

mysquares = square2(mylist)
for mysquare in mysquares:
    print(mysquare)
print(type(mysquares))
# Asking for the length of a generator throws an error:
print(f"The generator has {len(mysquares)} entries")  

As a list:
1225
4
215296
16
<class 'list'>
The list has 4 entries

As a generator:
1225
4
215296
16
<class 'generator'>


TypeError: object of type 'generator' has no len()

In [25]:
#This script creates in Python a list of headlines and shows two ways to count the number of characters of each string
headlines = ('US condemns South new terrorist  attacks', 'New elections forces UK to go back to the UE', 'Venezuelan president is dismissed')
#The first way is manual:
print('manual results:')
print(len(headlines[0]))
print(len(headlines[1]))
print(len(headlines[2]))
#and the second is using a for-loop
print('for-loop results:')
for x in headlines:
    print(len(x))

manual results:
40
44
33
for-loop results:
40
44
33


In [26]:
len_headlines= [len(x) for x in headlines]
print(len_headlines)

# The code above is a really useful shorthand and considered very 'pythonic'.
# It is equivalent to the more verbose code below:
len_headlines = []
for x in headlines:
    len_headlines.append(len(x))
print(len_headlines)

[40, 44, 33]
[40, 44, 33]


In [27]:
#Print the headline if it is < 40 characters
for x in headlines:                                                                                                       
  if len(x)<40:                                                                                                           
    print(x)

Venezuelan president is dismissed


In [28]:
#Print the headline if it is < 40 characters and print 'NaN' in the other cases
for x in headlines:
  if len(x)<40:
    print(x)
  elif len(x) == 44:
    print("What a coincidence!")
  else :
    print ('NaN')


NaN
What a coincidence!
Venezuelan president is dismissed
