In [1]:
!pip3 install numpy pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
a = 100
print(type(a))

<class 'int'>


In [4]:
a = 100
a = a*2    # equivalent to (shorter) a*=2
b = 50
c = a + b
print(a, b, c)

200 50 250


In [5]:
d = 20
print(type(d))
# forcing python to treat 20 as a float
d2 = 20.0
print(type(d2))

e = int(20.7)
print(type(e))
print(e)

f = True
print(type(f))
print(int(f))
print(int(False))

<class 'int'>
<class 'float'>
<class 'int'>
20
<class 'bool'>
1
0


In [6]:
text1 = "This is a text"
print(f"Type of text1: {type(text1)}")
text2 = "Using 'single' and \"double\" quotes"
text3 = 'Using \"single\" and "double" quotes'
print(f"Are text2 and text3 equal?{text2==text3}")

Type of text1: <class 'str'>
Are text2 and text3 equal?False


In [7]:
somebytes= text1.encode("utf-8")
print(type(somebytes))
print(somebytes)

<class 'bytes'>
b'This is a text'


In [8]:
scores = [8, 8, 7, 6, 9, 4, 9, 2, 8, 5]
print(type(scores))
countries = ["Netherlands", "Germany", "Spain"]
print(type(countries))


<class 'list'>
<class 'list'>


In [9]:
scores = ["8","8","7","6","9","4","9","2","8","5"]

print(scores[4])
print([scores[0], scores[9]])
print(scores[0:4])

# Convert the first 4 scores into numbers
# Note the use of a list comprehension [.. for ..]
# This will be explained in the section on loops
scores_new = [int(e) for e in scores[1:4]]
print(type(scores_new))
print(scores_new)

9
['8', '5']
['8', '8', '7', '6']
<class 'list'>
[8, 7, 6]


In [10]:
# Appending a new value to a list:
scores.append(7)

# Create a new list instead of overwriting:
scores4 = scores + [7]

# Removing an entry:
del scores[-10]

# Creating a list containing various ranges
list(range(1,21)) 
list(range(-5,6))    

# A range of fractions: 0, 0.2, 0.4, ... 1.0 
# Because range only handles integers, we first
#   make a range of 0, 2, etc, and divide by 10
my_sequence = [e/10 for e in range(0,11,2)]

In [11]:
my_list = [33, "Twitter", np.sqrt, [1,2,3,4]]
print(type(my_list))

# this resolves to sqrt(16):
print(my_list[2](16))

<class 'list'>
4.0


In [12]:
x = [1,2,3]
y = x
y[0] = 99
print(x)

[99, 2, 3]


In [13]:
a = {3, 4, 5}
my_list = [3, 2, 3, 2, 1]
b = set(my_list)
print(f"Set a: {a}; b: {b}")
print(f"intersect:  a & b = {a & b}")
print(f"union:      a | b = {a | b}")
print(f"difference: a - b = {a - b}")


Set a: {3, 4, 5}; b: {1, 2, 3}
intersect:  a & b = {3}
union:      a | b = {1, 2, 3, 4, 5}
difference: a - b = {4, 5}


In [14]:
sentiments = {"positive":1, "neutral" : 0, 
              "negative" : -1}
print(type(sentiments))
print("Sentiment for positive:", 
      sentiments["positive"])

grades =  {}
grades["A"] = 4
grades["B"] = 3
grades["C"] = 2
grades["D"] = 1

print(f"Grade for A: {grades['A']}")
print(grades)

<class 'dict'>
Sentiment for positive: 1
Grade for A: 4
{'A': 4, 'B': 3, 'C': 2, 'D': 1}


In [15]:
matrix = [[1, 2, 3], [4, 5, 6], [7,8,9]]
print(matrix)

array2d = np.array(matrix)
print(array2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
authors = pd.DataFrame({"age": [38, 36, 39], 
  "countries": ["Netherlands","Germany","Spain"], 
  "living_abroad": [False, True, True]})
print(authors)

   age    countries  living_abroad
0   38  Netherlands          False
1   36      Germany           True
2   39        Spain           True


In [1]:
sequence=statement1=statement2=statement3=range(1)

In [2]:
for val in sequence:
    statement1
    statement2
    statement3 

In [17]:
headlines = ["US condemns terrorist attacks", 
  "New elections forces UK to go back to the UE",
  "Venezuelan president is dismissed"]
# Manually counting each element
print("manual results:")
print(len(headlines[0]))
print(len(headlines[1]))
print(len(headlines[2]))
#and the second is using a for-loop
print("for-loop results:")
for x in headlines:
    print(len(x))

manual results:
29
44
33
for-loop results:
29
44
33


In [18]:
len_headlines= [len(x) for x in headlines]
print(len_headlines)

# Note: the "list comprehension" above is
#   equivalent to the more verbose code below:
len_headlines = []
for x in headlines:
    len_headlines.append(len(x))
print(len_headlines)

[29, 44, 33]
[29, 44, 33]


In [3]:
condition=other_condition=True

In [5]:
if condition:
    statement1
elif other_condition:
    statement2
else:
    statement3

In [19]:
for x in headlines:
  if len(x)<40:
    print(x)

US condemns terrorist attacks
Venezuelan president is dismissed


In [20]:
for x in headlines:
  if len(x)<30:
    print(x)
  elif len(x) == 44:
    print("What a coincidence!")
  else :
    print ("Too low")


US condemns terrorist attacks
What a coincidence!
Too low


In [6]:
statements=arg1=arg2=return_value=1

In [7]:
def f(par1, par2=0):
    statements
    return return_value   

result = f(arg1, arg2)
result = f(par1=arg1, par2=arg2)
result = f(arg1, par2=arg2)
result = f(arg1)

In [21]:
#The first function just computes 60% of the value
def perc_60(x):
  return x*0.6
print(perc_60(10))
print(perc_60(4))

# The second function only computes 60% it the
#  value is bigger than 5
def perc_60_cond(x):
  if x>5:
    return x*0.6
  else:
    return x
print(perc_60_cond(10))
print(perc_60_cond(4))

6.0
2.4
6.0
4


In [22]:
# Apply the function in a for-loop
scores = [3,4,5,7]
for x in scores:
  print(perc_60_cond(x))

3
4
5
4.2


In [23]:
mylist = [35,2,464,4]

def square1(somelist):
    listofsquares = []
    for i in somelist:
        listofsquares.append(i**2)
    return(listofsquares)

def square2(somelist):
    for i in somelist:
        yield i**2

print("As a list:")
mysquares = square1(mylist)
for mysquare in mysquares:
    print(mysquare)
print(type(mysquares))
print(f"The list has {len(mysquares)} entries")

    
print("\nAs a generator:")

mysquares = square2(mylist)
for mysquare in mysquares:
    print(mysquare)
print(type(mysquares))
# This throws an error (generators have no length)
print(f"mysquares has {len(mysquares)} entries")  

As a list:
1225
4
215296
16
<class 'list'>
The list has 4 entries

As a generator:
1225
4
215296
16
<class 'generator'>


TypeError: object of type 'generator' has no len()