In [1]:
install.packages("Rcmdr", dependencies=TRUE)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘ps’, ‘processx’, ‘clipr’, ‘BH’, ‘purrr’, ‘zip’, ‘DBI’, ‘plyr’, ‘farver’, ‘labeling’, ‘munsell’, ‘lifecycle’, ‘callr’, ‘coda’, ‘forcats’, ‘hms’, ‘readr’, ‘tidyselect’, ‘SparseM’, ‘MatrixModels’, ‘sp’, ‘curl’, ‘openxlsx’, ‘numDeriv’, ‘mitools’, ‘lazyeval’, ‘reshape2’, ‘scales’, ‘viridisLite’, ‘withr’, ‘png’, ‘jpeg’, ‘RColorBrewer’, ‘checkmate’, ‘rstudioapi’, ‘stringi’, ‘rematch’, ‘pkgconfig’, ‘prettyunits’, ‘R6’, ‘httpuv’, ‘xtable’, ‘sourcetools’, ‘later’, ‘promises’, ‘fastmap’, ‘miniUI’, ‘webshot’, ‘arm’, ‘sandwich’, ‘haven’, ‘readstata13’, ‘carData’, ‘pbkrtest’, ‘quantreg’, ‘maptools’, ‘rio’, ‘survey’, ‘estimability’, ‘minqa’, ‘nloptr’, ‘RcppEigen’, ‘Formula’, ‘ggplot2’, ‘latticeExtra’, ‘acepack’, ‘gtable’, ‘gridExtra’, ‘data.table’, ‘htmlTable’, ‘viridis’, ‘highr’, ‘stringr’, ‘yaml’, ‘xfun’, ‘zoo’, ‘mime’, ‘mvtnorm’, ‘TH.data’, ‘cellranger’, ‘tibble’, ‘progress’, ‘htmlw

In [5]:
a = 100
print(class(a))

[1] "numeric"


In [2]:
a = 100
a = a*2
b = 50
c = a + b
print(a)
print(b)
print(c)

[1] 200
[1] 50
[1] 250


In [29]:
d = 20
print(class(d))
# forcing R to treat 20 as an int
d2 = 20L
print(class(d2))

e = as.integer(20.7)
print(class(e))
print(e)

f = TRUE
print(class(f))
print(as.integer(f))
print(as.integer(FALSE))

[1] "numeric"
[1] "integer"
[1] "integer"
[1] 20
[1] "logical"
[1] 1
[1] 0


In [34]:
sometext = "I am happy learning R!"
print(class(sometext))
somebytes= charToRaw(sometext)
print(class(somebytes))

print("'Hi!' said he.")
print('"Hi!" said he.')

[1] "character"
[1] "raw"
[1] "'Hi!' said he."
[1] "\"Hi!\" said he."


In [3]:
scores = c(8, 8, 7, 6, 9, 4, 9, 2, 8, 5)
print(class(scores))
countries = c('Netherlands', 'Germany', 'Spain')
print(class(countries))


[1] "numeric"
[1] "character"


In [16]:
scores2 = c(8, 8, 7, 6, 9, 4, 9, 2, 8, 5,  'b')
print(class(scores2))
print(scores2)
print(scores)

[1] "character"
 [1] "8" "8" "7" "6" "9" "4" "9" "2" "8" "5" "b"
 [1] "8" "8" "7" "6" "9" "4" "9" "2" "8" "7" "7" "7" "7" "7"


In [11]:
scores = c("8", "8", "7", "6", "9", "4", "9", "2", "8", "5")

scores[5]
scores[c(1, 10)]
scores[1:4]

# taking the first 4 elements from scores2 and convert them back into numbers
scores_new = as.numeric(scores[1:4])
class(scores_new)
scores_new

[1] "9"

[1] "8" "5"

[1] "8" "8" "7" "6"

[1] "numeric"

[1] 8 8 7 6

In [14]:
# appending a new value to a vector
scores = c(scores, 7)
# alternative approach
scores = append(scores, 7)

# Of course, we could also store it in a different object instead of overwriting the original vector
scores4 = c(scores, 7)
# or
scores4 = append(scores, 7)

# removing an entry from a vector
scores = scores[-10]

# creating a vector containing the values 1,2,3,...20 (or -5, -4, ... 5)
range1 <- 1:20
range2 <- -5:5

# more advanced: 0, 0.2, 0.4, ... 1.0 
my_sequence = seq(0,1, by=0.2)

In [60]:
my_list = list(33, 'Twitter', sqrt, c(1,2,3,4))
class(my_list)

# this resolves to sqrt(16):
my_list[[3]](16)

[1] "list"

[1] 4

In [62]:
scores <- c(8, 8, 7, 6, 9, 4, 9, 2, 8, 5)                                                                                 
factor_scores <- factor(scores)                                                                                           
factor_scores_2 <- factor(scores, levels = c(1,2,3,4,5,6,7,8,9,10), labels = c("fail", "fail", "fail", "fail", "fail",
"pass", "pass", "pass", "pass", "pass"))

In [4]:
my_matrix <- matrix( c(0,0,1,1,0,1), nrow = 2, ncol = 3, byrow = TRUE)
print(dim(my_matrix))
print(my_matrix)

my_matrix2 <- matrix( c(0,0,1,1,0,1), nrow = 2, ncol = 3, byrow = FALSE)
print(my_matrix2)

my_matrix3 = my_matrix + my_matrix2
print(my_matrix3)

array3d <- array(c('green', 'yellow', 'red'),dim = c(3,3,3))
print(dim(array3d))
print(array3d)


[1] 2 3
     [,1] [,2] [,3]
[1,]    0    0    1
[2,]    1    0    1
     [,1] [,2] [,3]
[1,]    0    1    0
[2,]    0    1    1
     [,1] [,2] [,3]
[1,]    0    1    1
[2,]    1    1    2
[1] 3 3 3
, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"
[3,] "red"    "red"    "red"   

, , 2

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"
[3,] "red"    "red"    "red"   

, , 3

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"
[3,] "red"    "red"    "red"   



In [72]:
authors = data.frame(age = c(38, 36, 39), countries = c('Netherlands', 'Germany', 'Spain'), living_abroad= c(FALSE, TRUE, TRUE))
print(authors)

  age   countries living_abroad
1  38 Netherlands         FALSE
2  36     Germany          TRUE
3  39       Spain          TRUE


In [76]:
#This scripts in R creates two simple functions to estimate the 60% of any given number                                   

#The first function computes the 60% always                                                                               
por_60 <- function(x) {
  return(x*0.6)
}
print (por_60(10))
print (por_60(4))

#The second function computes the 60% ONLY IF the argument is above 5,                                                    
# and the other cases the function returns the very same argument

por_60_cond <- function(x) {
  if (x>5) {
    return(x*0.6)
  } else {
    return(x)
  }
}
print (por_60_cond(10))
print (por_60_cond(4))

[1] 6
[1] 2.4
[1] 6
[1] 4


In [75]:
#Create the list with the scores and then apply a simple loop
scores <- list(3,4,5,6,7)
for (x in scores)
{
  print(por_60_cond(x))
}

[1] 3
[1] 4
[1] 5
[1] 3.6
[1] 4.2


In [77]:
#This script creates in R a list of headlines and shows two ways to count the number of characters of each string
#The first way is manual
headlines <- list ('US condemns South new terrorist  attacks', 'New elections forces UK to go back to the UE',
'Venezuelan president is dismissed')
print('manual results:  ')
print(nchar(headlines[1]))
print(nchar(headlines[2]))
print(nchar(headlines[3]))
#and the second is using a for-loop
print('for-loop results:')
for (x in headlines){
  print(nchar(x))
}

[1] "manual results:  "
[1] 40
[1] 44
[1] 33
[1] "for-loop results:"
[1] 40
[1] 44
[1] 33


In [78]:
#Print the headline if it is < 40 characters
for (x in headlines){
  if (nchar(x)<40) {
    print(x)}
  }


[1] "Venezuelan president is dismissed"


In [81]:
#Print the headline if it is < 40 characters
for (x in headlines){
  if (nchar(x)<40) {
    print(x)}
  else if (nchar(x)==44) {print("What a coincidence!")}
else {print("NaN")}
  }


[1] "NaN"
[1] "What a coincidence!"
[1] "Venezuelan president is dismissed"
